---PROC
CREATE PROC SP_BANGDIEM (@MAKH INT)
AS BEGIN
	SELECT NH.MANH, NH.HOTEN, HV.DIEM
	FROM HOCVIEN AS HV JOIN NGUOIHOC AS NH
	ON HV.MANH = NH.MANH
	WHERE HV.MAKH = @MAKH
	ORDER BY HV.DIEM DESC
END
---PROC
CREATE PROC SP_LUONGNGUOIHOC
AS BEGIN
	SELECT YEAR(NGAYDK) NAM, COUNT(*) SOLUONG,
	MIN(NGAYDK) DAUTIEN, MAX(NGAYDK) CUOICUNG
	FROM NGUOIHOC
	GROUP BY YEAR(NGAYDK)
END
---PROC
CREATE PROC SP_DIEMCHUYENDE
AS BEGIN
	SELECT TENCD, COUNT(MAHV) SOHV, MIN(DIEM) THAPNHAT,
	MAX(DIEM) CAONHAT, AVG(DIEM) TRUNGBINH
	FROM KHOAHOC AS KH JOIN HOCVIEN AS HV
	ON KH.MAKH = HV.MAKH JOIN CHUYENDE AS CD
	ON CD.MACD = KH.MACD
	GROUP BY TENCD
END
---PROC
CREATE PROC SP_DOANHTHU (@YEAR INT)
AS BEGIN
	SELECT TENCD, COUNT(DISTINCT KH.MAKH) SOKH,
	COUNT(HV.MAHV) SOHV, SUM(KH.HOCPHI) DOANHTHU,
	MIN(KH.HOCPHI) THAPNHAT,
	MAX(KH.HOCPHI) CAONHAT,
	AVG(KH.HOCPHI) TRUNGBINH
	FROM KHOAHOC AS KH JOIN HOCVIEN AS HV
	ON KH.MAKH = HV.MAKH JOIN CHUYENDE AS CD
	ON CD.MACD = KH.MACD
	WHERE YEAR(NGAYKG) = @YEAR
	GROUP BY TENCD
END
---PROC
CREATE PROC PROC_GETID
	(@TABLE_NAME VARCHAR(30))
AS
	IF(@TABLE_NAME IS NULL)
		PRINT N'DỮ LIỆU NHẬP VÀO KHÔNG HỢP LỆ'
	ELSE
		DECLARE @LASSTID INT
		SET @LASSTID = IDENT_CURRENT(@TABLE_NAME)
		SELECT @LASSTID
