---TABLE
CREATE TABLE CHUYENDE (
	MACD VARCHAR(10) NOT NULL,
	TENCD NVARCHAR(50) NOT NULL,
	HOCPHI MONEY NOT NULL,
	THOILUONG INT NOT NULL CHECK (THOILUONG > 0),
	HINH NVARCHAR(50) NOT NULL,
	MOTA NTEXT

	CONSTRAINT PK_CHUYENDE PRIMARY KEY (MACD)
)
---TABLE
CREATE TABLE NHANVIEN (
	MANV VARCHAR(10) NOT NULL,
	MATKHAU NVARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	VAITRO BIT DEFAULT 0
	
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
)
---TABLE
CREATE TABLE KHOAHOC (
	MAKH INT IDENTITY (1,1),
	MACD VARCHAR(10),
	HOCPHI MONEY NOT NULL,
	THOILUONG INT NOT NULL CHECK (THOILUONG > 0),
	NGAYKG DATETIME NOT NULL,
	GHICHU NTEXT,
	MANV VARCHAR(10),
	NGAYTAO DATETIME DEFAULT GETDATE()

	CONSTRAINT PK_KHOAHOC PRIMARY KEY (MAKH),
	CONSTRAINT FK_KHOAHOC_CHUYENDE FOREIGN KEY (MACD) REFERENCES CHUYENDE (MACD)
	ON DELETE NO ACTION
	ON UPDATE CASCADE,
	CONSTRAINT FK_KHOAHOC_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)
	ON DELETE NO ACTION
	ON UPDATE CASCADE
)
---TABLE
CREATE TABLE NGUOIHOC (
	MANH VARCHAR(10) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	GIOITINH BIT DEFAULT 1,
	NGAYSINH DATETIME NOT NULL,
	DIENTHOAI VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	GHICHU NTEXT,
	MANV VARCHAR(10),
	NGAYDK DATETIME DEFAULT GETDATE()
	
	CONSTRAINT PK_NGUOIHOC PRIMARY KEY (MANH),
	CONSTRAINT FK_NGUOIHOC_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)
	ON DELETE NO ACTION
	ON UPDATE CASCADE
)
---TABLE
CREATE TABLE HOCVIEN (
	MAHV INT IDENTITY (1,1),
	MAKH INT,
	MANH VARCHAR(10),
	DIEM FLOAT DEFAULT 0

	CONSTRAINT PK_HOCVIEN PRIMARY KEY (MAHV),
	CONSTRAINT FK_HOCVIEN_KHOAHOC FOREIGN KEY (MAKH) REFERENCES KHOAHOC (MAKH),
	CONSTRAINT FK_HOCVIEN_NGUOIHOC FOREIGN KEY (MANH) REFERENCES NGUOIHOC (MANH)
)
---TABLE
--CREATE
INSERT NHANVIEN (MANV, MATKHAU, HOTEN, VAITRO)
VALUES ('ADMIN', '12345678', N'NGUYỄN QUANG NGỌC', 1)
